/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
/**
 *
 * @author toan
 */
public class addComponent extends javax.swing.JFrame implements ActionListener{
        String nameFree = "free.jpeg";
        String namePice[] = new String[13];
        String nameBuffer[] = new String[13];//ten cua image area hien tai
        String varBuffer;//dung de trao doi ten image area
    //ImageIcon  img ;//main image
    
    ImageIcon icon1 = new ImageIcon("anh1.jpg");
    ImageIcon icon2 = new ImageIcon("anh2.jpg");
    ImageIcon icon3 = new ImageIcon("anh3.jpg");
    ImageIcon icon4 = new ImageIcon("anh4.jpg");
    ImageIcon icon5 = new ImageIcon("anh5.jpg");
    /*ImageIcon pice[] = new ImageIcon[13]; */
    //int followIcon = 0;
    static int count = 0;
    int t = 0;
    int random = 0;
    boolean idle[] = new boolean[13];
    boolean runtime;
    int stateNow[] = new int[13];
    static int countTime = 0;//tinh thoi gian choi
    
    static int timeWin,taskWin;
    boolean win;
   //int buffer1,buffer2;
    public addComponent() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        task = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        displayTask = new javax.swing.JLabel();
        displayTime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        area10 = new javax.swing.JLabel();
        area2 = new javax.swing.JLabel();
        area3 = new javax.swing.JLabel();
        area1 = new javax.swing.JLabel();
        area5 = new javax.swing.JLabel();
        area6 = new javax.swing.JLabel();
        area4 = new javax.swing.JLabel();
        area8 = new javax.swing.JLabel();
        area9 = new javax.swing.JLabel();
        area7 = new javax.swing.JLabel();
        area11 = new javax.swing.JLabel();
        area12 = new javax.swing.JLabel();
        areaIdle = new javax.swing.JLabel();
        rePlay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        displayTask1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        button.setText("change Image");
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button);
        button.setBounds(31, 59, 150, 30);
        getContentPane().add(label);
        label.setBounds(12, 112, 200, 150);

        jButton1.setText("choose file");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 12, 120, 30);

        jButton2.setText("exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(134, 12, 140, 30);

        task.setText("task");
        getContentPane().add(task);
        task.setBounds(20, 360, 40, 20);

        time.setText("time");
        getContentPane().add(time);
        time.setBounds(20, 340, 40, 20);
        getContentPane().add(displayTask);
        displayTask.setBounds(80, 360, 83, 20);
        getContentPane().add(displayTime);
        displayTime.setBounds(80, 340, 83, 20);

        jPanel1.setBackground(new java.awt.Color(180, 246, 229));
        jPanel1.setLayout(null);

        area10.setOpaque(true);
        area10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area10MouseClicked(evt);
            }
        });
        jPanel1.add(area10);
        area10.setBounds(89, 210, 66, 66);

        area2.setOpaque(true);
        area2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area2MouseClicked(evt);
            }
        });
        jPanel1.add(area2);
        area2.setBounds(89, 78, 66, 66);

        area3.setOpaque(true);
        area3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area3MouseClicked(evt);
            }
        });
        jPanel1.add(area3);
        area3.setBounds(155, 78, 66, 66);

        area1.setOpaque(true);
        area1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area1MouseClicked(evt);
            }
        });
        jPanel1.add(area1);
        area1.setBounds(23, 78, 66, 66);

        area5.setOpaque(true);
        area5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area5MouseClicked(evt);
            }
        });
        jPanel1.add(area5);
        area5.setBounds(23, 144, 66, 66);

        area6.setOpaque(true);
        area6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area6MouseClicked(evt);
            }
        });
        jPanel1.add(area6);
        area6.setBounds(89, 144, 66, 66);

        area4.setOpaque(true);
        area4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area4MouseClicked(evt);
            }
        });
        jPanel1.add(area4);
        area4.setBounds(220, 78, 66, 66);

        area8.setOpaque(true);
        area8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area8MouseClicked(evt);
            }
        });
        jPanel1.add(area8);
        area8.setBounds(221, 144, 66, 66);

        area9.setOpaque(true);
        area9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area9MouseClicked(evt);
            }
        });
        jPanel1.add(area9);
        area9.setBounds(23, 210, 66, 66);

        area7.setOpaque(true);
        area7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area7MouseClicked(evt);
            }
        });
        jPanel1.add(area7);
        area7.setBounds(155, 144, 66, 66);

        area11.setOpaque(true);
        area11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area11MouseClicked(evt);
            }
        });
        jPanel1.add(area11);
        area11.setBounds(155, 210, 66, 66);

        area12.setOpaque(true);
        area12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                area12MouseClicked(evt);
            }
        });
        jPanel1.add(area12);
        area12.setBounds(221, 210, 66, 66);

        areaIdle.setText("    IDLE");
        areaIdle.setOpaque(true);
        areaIdle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areaIdleMouseClicked(evt);
            }
        });
        jPanel1.add(areaIdle);
        areaIdle.setBounds(220, 12, 66, 66);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(270, 79, 320, 400);

        rePlay.setText("re play");
        rePlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rePlayActionPerformed(evt);
            }
        });
        getContentPane().add(rePlay);
        rePlay.setBounds(390, 40, 130, 30);

        jLabel1.setText("best score");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 390, 90, 18);

        displayTask1.setText("28");
        getContentPane().add(displayTask1);
        displayTask1.setBounds(90, 390, 83, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
        // TODO add your handling code here:
        t ++;
        runtime = true;
        countTime = 0;
        random = 0;
        if(t == 6){
            t = 1;
            //followIcon = t;
        }
        count = 0;
        displayTask.setText("");
        //public void followIcon(){
         // switch(followIcon){
                              
              
     // }
       // followIcon();
        switch(t){
            case 1: /*pice[1] = new ImageIcon("anh1_1.jpeg");
                    pice[2] = new ImageIcon("anh1_2.jpeg");
                    pice[3] = new ImageIcon("anh1_3.jpeg");
                    pice[4] = new ImageIcon("anh1_4.jpeg");
                    pice[5] = new ImageIcon("anh1_5.jpeg");
                    pice[6] = new ImageIcon("anh1_6.jpeg");
                    pice[7] = new ImageIcon("anh1_7.jpeg");
                    pice[8] = new ImageIcon("anh1_8.jpeg");
                    pice[9] = new ImageIcon("anh1_9.jpeg");
                    pice[10] = new ImageIcon("anh1_10.jpeg");
                    pice[11] = new ImageIcon("anh1_11.jpeg");
                    pice[12] = new ImageIcon("anh1_12.jpeg"); */
                    namePice[1] = "anh1_1.jpeg";
                    namePice[2] = "anh1_2.jpeg";
                    namePice[3] = "anh1_3.jpeg";
                    namePice[4] = "anh1_4.jpeg";
                    namePice[5] = "anh1_5.jpeg";
                    namePice[6] = "anh1_6.jpeg";
                    namePice[7] = "anh1_7.jpeg";
                    namePice[8] = "anh1_8.jpeg";
                    namePice[9] = "anh1_9.jpeg";
                    namePice[10] = "anh1_10.jpeg";
                    namePice[11] = "anh1_11.jpeg";
                    namePice[12] = "anh1_12.jpeg";
                    //set picture in all area
                    
                    setPicture(area1,namePice[2]);
                    setPicture(area2,namePice[9]);
                    setPicture(area3,namePice[11]);
                    setPicture(area4,namePice[4]);
                    setPicture(area5,namePice[12]);
                    setPicture(area6,namePice[6]);
                    setPicture(area7,namePice[3]);
                    setPicture(area8,namePice[8]);
                    setPicture(area9,namePice[7]);
                    setPicture(area10,namePice[5]);
                    setPicture(area11,namePice[10]);
                    setPicture(area12,namePice[1]);
                    setPicture(areaIdle,nameFree);
                    //change nameBuffered
                    nameBuffer[0]= nameFree;
                    nameBuffer[1]= namePice[2];
                    nameBuffer[2]= namePice[9];
                    nameBuffer[3]= namePice[11];
                    nameBuffer[4]= namePice[4];
                    nameBuffer[5]= namePice[12];
                    nameBuffer[6]= namePice[6];
                    nameBuffer[7]= namePice[3];
                    nameBuffer[8]= namePice[8];
                    nameBuffer[9]= namePice[7];
                    nameBuffer[10]= namePice[5];
                    nameBuffer[11]= namePice[10];
                    nameBuffer[12]= namePice[1];
                    
                    resetIdle();    
                    setPicture(label,"anh1.jpg");                    
                    
                    //img = new ImageIcon("anh1_1.jpg");
                    break;
            case 2:/* pice[1] = new ImageIcon("anh2_1.jpeg");
                    pice[2] = new ImageIcon("anh2_2.jpeg");
                    pice[3] = new ImageIcon("anh2_3.jpeg");
                    pice[4] = new ImageIcon("anh2_4.jpeg");
                    pice[5] = new ImageIcon("anh2_5.jpeg");
                    pice[6] = new ImageIcon("anh2_6.jpeg");
                    pice[7] = new ImageIcon("anh2_7.jpeg");
                    pice[8] = new ImageIcon("anh2_8.jpeg");
                    pice[9] = new ImageIcon("anh2_9.jpeg");
                    pice[10] = new ImageIcon("anh2_10.jpeg");
                    pice[11] = new ImageIcon("anh2_11.jpeg");
                    pice[12] = new ImageIcon("anh2_12.jpeg"); */
                    namePice[1] = "anh2_1.jpeg";
                    namePice[2] = "anh2_2.jpeg";
                    namePice[3] = "anh2_3.jpeg";
                    namePice[4] = "anh2_4.jpeg";
                    namePice[5] = "anh2_5.jpeg";
                    namePice[6] = "anh2_6.jpeg";
                    namePice[7] = "anh2_7.jpeg";
                    namePice[8] = "anh2_8.jpeg";
                    namePice[9] = "anh2_9.jpeg";
                    namePice[10] = "anh2_10.jpeg";
                    namePice[11] = "anh2_11.jpeg";
                    namePice[12] = "anh2_12.jpeg";
                    setPicture(area1,namePice[2]);
                    setPicture(area2,namePice[9]);
                    setPicture(area3,namePice[11]);
                    setPicture(area4,namePice[4]);
                    setPicture(area5,namePice[12]);
                    setPicture(area6,namePice[6]);
                    setPicture(area7,namePice[3]);
                    setPicture(area8,namePice[8]);
                    setPicture(area9,namePice[7]);
                    setPicture(area10,namePice[5]);
                    setPicture(area11,namePice[10]);
                    setPicture(area12,namePice[1]);
                    setPicture(areaIdle,nameFree);
                    //
                    nameBuffer[0]= nameFree;
                    nameBuffer[1]= namePice[2];
                    nameBuffer[2]= namePice[9];
                    nameBuffer[3]= namePice[11];
                    nameBuffer[4]= namePice[4];
                    nameBuffer[5]= namePice[12];
                    nameBuffer[6]= namePice[6];
                    nameBuffer[7]= namePice[3];
                    nameBuffer[8]= namePice[8];
                    nameBuffer[9]= namePice[7];
                    nameBuffer[10]= namePice[5];
                    nameBuffer[11]= namePice[10];
                    nameBuffer[12]= namePice[1];
                    
                    ///
                    resetIdle();
                    setPicture(label,"anh2.jpg");
                    //img = new ImageIcon("anh2.jpg");
                    //setPicture(area4,namePice[1]);
                    break;
            case 3: /* pice[1] = new ImageIcon("anh3_1.jpeg");
                    pice[2] = new ImageIcon("anh3_2.jpeg");
                    pice[3] = new ImageIcon("anh3_3.jpeg");
                    pice[4] = new ImageIcon("anh3_4.jpeg");
                    pice[5] = new ImageIcon("anh3_5.jpeg");
                    pice[6] = new ImageIcon("anh3_6.jpeg");
                    pice[7] = new ImageIcon("anh3_7.jpeg");
                    pice[8] = new ImageIcon("anh3_8.jpeg");
                    pice[9] = new ImageIcon("anh3_9.jpeg");
                    pice[10] = new ImageIcon("anh3_10.jpeg");
                    pice[11] = new ImageIcon("anh3_11.jpeg");
                    pice[12] = new ImageIcon("anh3_12.jpeg"); */
                    namePice[1] = "anh3_1.jpeg";
                    namePice[2] = "anh3_2.jpeg";
                    namePice[3] = "anh3_3.jpeg";
                    namePice[4] = "anh3_4.jpeg";
                    namePice[5] = "anh3_5.jpeg";
                    namePice[6] = "anh3_6.jpeg";
                    namePice[7] = "anh3_7.jpeg";
                    namePice[8] = "anh3_8.jpeg";
                    namePice[9] = "anh3_9.jpeg";
                    namePice[10] = "anh3_10.jpeg";
                    namePice[11] = "anh3_11.jpeg";
                    namePice[12] = "anh3_12.jpeg";
                    setPicture(area1,namePice[2]);
                    setPicture(area2,namePice[9]);
                    setPicture(area3,namePice[11]);
                    setPicture(area4,namePice[4]);
                    setPicture(area5,namePice[12]);
                    setPicture(area6,namePice[6]);
                    setPicture(area7,namePice[3]);
                    setPicture(area8,namePice[8]);
                    setPicture(area9,namePice[7]);
                    setPicture(area10,namePice[5]);
                    setPicture(area11,namePice[10]);
                    setPicture(area12,namePice[1]);
                    setPicture(areaIdle,nameFree);
                    ///
                    nameBuffer[0]= nameFree;
                    nameBuffer[1]= namePice[2];
                    nameBuffer[2]= namePice[9];
                    nameBuffer[3]= namePice[11];
                    nameBuffer[4]= namePice[4];
                    nameBuffer[5]= namePice[12];
                    nameBuffer[6]= namePice[6];
                    nameBuffer[7]= namePice[3];
                    nameBuffer[8]= namePice[8];
                    nameBuffer[9]= namePice[7];
                    nameBuffer[10]= namePice[5];
                    nameBuffer[11]= namePice[10];
                    nameBuffer[12]= namePice[1];
                    ///
                    resetIdle();
                    setPicture(label,"anh3.jpg");//main picture
                    //img = new ImageIcon("anh3.jpg");
                    break;
            case 4: /*pice[1] = new ImageIcon("anh4_1.jpeg");
                    pice[2] = new ImageIcon("anh4_2.jpeg");
                    pice[3] = new ImageIcon("anh4_3.jpeg");
                    pice[4] = new ImageIcon("anh4_4.jpeg");
                    pice[5] = new ImageIcon("anh4_5.jpeg");
                    pice[6] = new ImageIcon("anh4_6.jpeg");
                    pice[7] = new ImageIcon("anh4_7.jpeg");
                    pice[8] = new ImageIcon("anh4_8.jpeg");
                    pice[9] = new ImageIcon("anh4_9.jpeg");
                    pice[10] = new ImageIcon("anh4_10.jpeg");
                    pice[11] = new ImageIcon("anh4_11.jpeg");
                    pice[12] = new ImageIcon("anh4_12.jpeg"); */
                    namePice[1] = "anh4_1.jpeg";
                    namePice[2] = "anh4_2.jpeg";
                    namePice[3] = "anh4_3.jpeg";
                    namePice[4] = "anh4_4.jpeg";
                    namePice[5] = "anh4_5.jpeg";
                    namePice[6] = "anh4_6.jpeg";
                    namePice[7] = "anh4_7.jpeg";
                    namePice[8] = "anh4_8.jpeg";
                    namePice[9] = "anh4_9.jpeg";
                    namePice[10] = "anh4_10.jpeg";
                    namePice[11] = "anh4_11.jpeg";
                    namePice[12] = "anh4_12.jpeg";
                    setPicture(label,"anh4.jpg");//main picture
                    setPicture(area1,namePice[2]);
                    setPicture(area2,namePice[9]);
                    setPicture(area3,namePice[11]);
                    setPicture(area4,namePice[4]);
                    setPicture(area5,namePice[12]);
                    setPicture(area6,namePice[6]);
                    setPicture(area7,namePice[3]);
                    setPicture(area8,namePice[8]);
                    setPicture(area9,namePice[7]);
                    setPicture(area10,namePice[5]);
                    setPicture(area11,namePice[10]);
                    setPicture(area12,namePice[1]);
                    setPicture(areaIdle,nameFree);
                    ///
                    nameBuffer[0]= nameFree;
                    nameBuffer[1]= namePice[2];
                    nameBuffer[2]= namePice[9];
                    nameBuffer[3]= namePice[11];
                    nameBuffer[4]= namePice[4];
                    nameBuffer[5]= namePice[12];
                    nameBuffer[6]= namePice[6];
                    nameBuffer[7]= namePice[3];
                    nameBuffer[8]= namePice[8];
                    nameBuffer[9]= namePice[7];
                    nameBuffer[10]= namePice[5];
                    nameBuffer[11]= namePice[10];
                    nameBuffer[12]= namePice[1];
                    ///
                    resetIdle();
                    //img = new ImageIcon("anh4.jpg");
                    break;
            case 5:  /*pice[1] = new ImageIcon("anh5_1.jpeg");
                    pice[2] = new ImageIcon("anh5_2.jpeg");
                    pice[3] = new ImageIcon("anh5_3.jpeg");
                    pice[4] = new ImageIcon("anh5_4.jpeg");
                    pice[5] = new ImageIcon("anh5_5.jpeg");
                    pice[6] = new ImageIcon("anh5_6.jpeg");
                    pice[7] = new ImageIcon("anh5_7.jpeg");
                    pice[8] = new ImageIcon("anh5_8.jpeg");
                    pice[9] = new ImageIcon("anh5_9.jpeg");
                    pice[10] = new ImageIcon("anh5_10.jpeg");
                    pice[11] = new ImageIcon("anh5_11.jpeg");
                    pice[12] = new ImageIcon("anh5_12.jpeg"); */
                    namePice[1] = "anh5_1.jpeg";
                    namePice[2] = "anh5_2.jpeg";
                    namePice[3] = "anh5_3.jpeg";
                    namePice[4] = "anh5_4.jpeg";
                    namePice[5] = "anh5_5.jpeg";
                    namePice[6] = "anh5_6.jpeg";
                    namePice[7] = "anh5_7.jpeg";
                    namePice[8] = "anh5_8.jpeg";
                    namePice[9] = "anh5_9.jpeg";
                    namePice[10] = "anh5_10.jpeg";
                    namePice[11] = "anh5_11.jpeg";
                    namePice[12] = "anh5_12.jpeg";
                    setPicture(label,"anh5.jpg");//main picture
                    setPicture(area1,namePice[2]);//setup area first
                    setPicture(area2,namePice[9]);
                    setPicture(area3,namePice[11]);
                    setPicture(area4,namePice[4]);
                    setPicture(area5,namePice[12]);
                    setPicture(area6,namePice[6]);
                    setPicture(area7,namePice[3]);
                    setPicture(area8,namePice[8]);
                    setPicture(area9,namePice[7]);
                    setPicture(area10,namePice[5]);
                    setPicture(area11,namePice[10]);
                    setPicture(area12,namePice[1]);
                    setPicture(areaIdle,nameFree);
                    ////
                    nameBuffer[0]= nameFree;
                    nameBuffer[1]= namePice[2];
                    nameBuffer[2]= namePice[9];
                    nameBuffer[3]= namePice[11];
                    nameBuffer[4]= namePice[4];
                    nameBuffer[5]= namePice[12];
                    nameBuffer[6]= namePice[6];
                    nameBuffer[7]= namePice[3];
                    nameBuffer[8]= namePice[8];
                    nameBuffer[9]= namePice[7];
                    nameBuffer[10]= namePice[5];
                    nameBuffer[11]= namePice[10];
                    nameBuffer[12]= namePice[1];
                    ////
                    resetIdle();
                    //img = new ImageIcon("anh5.jpg");
                    break;
            
        }
        
    }//GEN-LAST:event_buttonMouseClicked
    public void random(int ran){
        switch(ran){
            case 1:
                setPicture(areaIdle,nameFree);
                setPicture(area1,namePice[1]);stateNow[1] = 1;
                setPicture(area2,namePice[9]);stateNow[2] = 9;
                setPicture(area3,namePice[6]);stateNow[3] = 6;
                setPicture(area4,namePice[4]);stateNow[4] = 4;
                setPicture(area5,namePice[12]);stateNow[5] = 12;
                setPicture(area6,namePice[11]);stateNow[6] = 11;
                setPicture(area7,namePice[7]);stateNow[7] = 7;
                setPicture(area8,namePice[8]);stateNow[8] = 8;
                setPicture(area9,namePice[3]);stateNow[9] = 3;
                setPicture(area10,namePice[10]);stateNow[10] = 10;
                setPicture(area11,namePice[2]);stateNow[11] = 2;
                setPicture(area12,namePice[5]);stateNow[12] = 5;
                nameBuffer[0]= nameFree;
                nameBuffer[1]= namePice[1];
                nameBuffer[2]= namePice[9];
                nameBuffer[3]= namePice[6];
                nameBuffer[4]= namePice[4];
                nameBuffer[5]= namePice[12];
                nameBuffer[6]= namePice[11];
                nameBuffer[7]= namePice[7];
                nameBuffer[8]= namePice[8];
                nameBuffer[9]= namePice[3];
                nameBuffer[10]= namePice[10];
                nameBuffer[11]= namePice[2];
                nameBuffer[12]= namePice[5];
                resetIdle();
                countTime = 0;
                break;
            case 2:
                setPicture(areaIdle,nameFree);
                setPicture(area1,namePice[6]);stateNow[1] = 6;
                setPicture(area2,namePice[9]);stateNow[2] = 9;
                setPicture(area3,namePice[3]);stateNow[3] = 3;
                setPicture(area4,namePice[4]);stateNow[4] = 4;
                setPicture(area5,namePice[1]);stateNow[5] = 1;
                setPicture(area6,namePice[11]);stateNow[6] = 11;
                setPicture(area7,namePice[2]);stateNow[7] = 2;
                setPicture(area8,namePice[8]);stateNow[8] = 8;
                setPicture(area9,namePice[5]);stateNow[9] = 5;
                setPicture(area10,namePice[12]);stateNow[10] = 12;
                setPicture(area11,namePice[7]);stateNow[11] = 7;
                setPicture(area12,namePice[10]);stateNow[12] = 10;
                nameBuffer[0]= nameFree;
                nameBuffer[1]= namePice[6];
                nameBuffer[2]= namePice[9];
                nameBuffer[3]= namePice[3];
                nameBuffer[4]= namePice[4];
                nameBuffer[5]= namePice[1];
                nameBuffer[6]= namePice[11];
                nameBuffer[7]= namePice[2];
                nameBuffer[8]= namePice[8];
                nameBuffer[9]= namePice[5];
                nameBuffer[10]= namePice[12];
                nameBuffer[11]= namePice[7];
                nameBuffer[12]= namePice[10];
                resetIdle();
                countTime = 0;
                break;
            case 3:
                setPicture(areaIdle,nameFree);
                setPicture(area1,namePice[2]);stateNow[1] = 2;
                setPicture(area2,namePice[8]);stateNow[2] = 8;
                setPicture(area3,namePice[11]);stateNow[3] = 11;
                setPicture(area4,namePice[4]);stateNow[4] = 4;
                setPicture(area5,namePice[1]);stateNow[5] = 1;
                setPicture(area6,namePice[7]);stateNow[6] = 7;
                setPicture(area7,namePice[12]);stateNow[7] = 12;
                setPicture(area8,namePice[6]);stateNow[8] = 6;
                setPicture(area9,namePice[9]);stateNow[9] = 9;
                setPicture(area10,namePice[5]);stateNow[10] = 5;
                setPicture(area11,namePice[3]);stateNow[11] = 3;
                setPicture(area12,namePice[10]);stateNow[12] = 10;
                nameBuffer[0]= nameFree;
                nameBuffer[1]= namePice[2];
                nameBuffer[2]= namePice[8];
                nameBuffer[3]= namePice[11];
                nameBuffer[4]= namePice[5];
                nameBuffer[5]= namePice[1];
                nameBuffer[6]= namePice[7];
                nameBuffer[7]= namePice[12];
                nameBuffer[8]= namePice[6];
                nameBuffer[9]= namePice[9];
                nameBuffer[10]= namePice[5];
                nameBuffer[11]= namePice[3];
                nameBuffer[12]= namePice[10];
                resetIdle();
                countTime = 0;
                break;
            case 4:
                setPicture(areaIdle,nameFree);
                setPicture(area1,namePice[6]);stateNow[1] = 6;
                setPicture(area2,namePice[12]);stateNow[2] = 12;
                setPicture(area3,namePice[3]);stateNow[3] = 3;
                setPicture(area4,namePice[4]);stateNow[4] = 4;
                setPicture(area5,namePice[11]);stateNow[5] = 11;
                setPicture(area6,namePice[8]);stateNow[6] = 8;
                setPicture(area7,namePice[9]);stateNow[7] = 9;
                setPicture(area8,namePice[5]);stateNow[8] = 5;
                setPicture(area9,namePice[1]);stateNow[9] = 1;
                setPicture(area10,namePice[10]);stateNow[10] = 10;
                setPicture(area11,namePice[2]);stateNow[11] = 2;
                setPicture(area12,namePice[7]);stateNow[12] = 7;
                nameBuffer[0]= nameFree;
                nameBuffer[1]= namePice[6];
                nameBuffer[2]= namePice[12];
                nameBuffer[3]= namePice[3];
                nameBuffer[4]= namePice[8];
                nameBuffer[5]= namePice[11];
                nameBuffer[6]= namePice[4];
                nameBuffer[7]= namePice[9];
                nameBuffer[8]= namePice[5];
                nameBuffer[9]= namePice[1];
                nameBuffer[10]= namePice[10];
                nameBuffer[11]= namePice[2];
                nameBuffer[12]= namePice[7];
                resetIdle();
                countTime = 0;
                break;
            case 5:
                setPicture(areaIdle,nameFree);
                setPicture(area1,namePice[1]);stateNow[1] = 1;
                setPicture(area2,namePice[2]);stateNow[2] = 2;
                setPicture(area3,namePice[3]);stateNow[3] = 3;
                setPicture(area4,namePice[4]);stateNow[4] = 4;
                setPicture(area5,namePice[5]);stateNow[5] = 5;
                setPicture(area6,namePice[6]);stateNow[6] = 6;
                setPicture(area7,namePice[7]);stateNow[7] = 7;
                setPicture(area8,namePice[8]);stateNow[8] = 8;
                setPicture(area9,namePice[9]);stateNow[9] = 9;
                setPicture(area10,namePice[10]);stateNow[10] = 10;
                setPicture(area11,namePice[11]);stateNow[11] = 11;
                setPicture(area12,namePice[12]);stateNow[12] = 12;
                nameBuffer[0]= nameFree;
                nameBuffer[1]= namePice[1];
                nameBuffer[2]= namePice[2];
                nameBuffer[3]= namePice[3];
                nameBuffer[4]= namePice[4];
                nameBuffer[5]= namePice[5];
                nameBuffer[6]= namePice[6];
                nameBuffer[7]= namePice[7];
                nameBuffer[8]= namePice[8];
                nameBuffer[9]= namePice[9];
                nameBuffer[10]= namePice[10];
                nameBuffer[11]= namePice[11];
                nameBuffer[12]= namePice[12];
                resetIdle();
                countTime = 0;

                break;
                
            
        }
    }
    
    //choose image to display 
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
				String name = chooser.getSelectedFile().getPath();
                                System.out.println(name);
                               //
                                //ImageIcon icon1 = new ImageIcon(name);
                                // chua chay icon1  = new ImageIcon(image.getScaledInstance(dx, dy, image.SCALE_SMOOTH));
				setPicture(label,name);
            try {
                Split split = new Split(name,3,4);
                //setup namepice
                namePice[1] = "img1.jpg";
                namePice[2] = "img2.jpg";
                namePice[3] = "img3.jpg";
                namePice[4] = "img4.jpg";
                namePice[5] = "img5.jpg";
                namePice[6] = "img6.jpg";
                namePice[7] = "img7.jpg";
                namePice[8] = "img8.jpg";
                namePice[9] = "img9.jpg";
                namePice[10] = "img10.jpg";
                namePice[11] = "img11.jpg";
                namePice[12] = "img12.jpg";
                
                /////////
                setPicture(areaIdle,nameFree);
                setPicture(area1,namePice[12]);stateNow[1] = 12;
                setPicture(area2,namePice[2]);stateNow[2] = 2;
                setPicture(area3,namePice[3]);stateNow[3] = 3;
                setPicture(area4,namePice[4]);stateNow[4] = 4;
                setPicture(area5,namePice[5]);stateNow[5] = 5;
                setPicture(area6,namePice[6]);stateNow[6] = 6;
                setPicture(area7,namePice[7]);stateNow[7] = 7;
                setPicture(area8,namePice[8]);stateNow[8] = 8;
                setPicture(area9,namePice[9]);stateNow[9] = 9;
                setPicture(area10,namePice[10]);stateNow[10] = 10;
                setPicture(area11,namePice[11]);stateNow[11] = 11;
                setPicture(area12,namePice[1]);stateNow[12] = 1;
                nameBuffer[0]= nameFree;
                nameBuffer[1]= namePice[12];
                nameBuffer[2]= namePice[2];
                nameBuffer[3]= namePice[3];
                nameBuffer[4]= namePice[4];
                nameBuffer[5]= namePice[5];
                nameBuffer[6]= namePice[6];
                nameBuffer[7]= namePice[7];
                nameBuffer[8]= namePice[8];
                nameBuffer[9]= namePice[9];
                nameBuffer[10]= namePice[10];
                nameBuffer[11]= namePice[11];
                nameBuffer[12]= namePice[1];
                resetIdle();
                countTime = 0;
                runtime = true;
                
            } catch (IOException ex) {
                //Logger.getLogger(addComponent.class.getName()).log(Level.SEVERE, null, ex);
            }
                                
			}
    }//GEN-LAST:event_jButton1MouseClicked
    //sort the icon
      
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rePlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rePlayActionPerformed
        // TODO add your handling code here:
        random ++;
        if(random == 6)
            random = 1;
        random(random);
        count = 0;
        displayTask.setText("");
    }//GEN-LAST:event_rePlayActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonActionPerformed

    private void area4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area4MouseClicked
        // TODO add your handling code here:
        //look at area4
        if(idle[4] == false){
            if(idle[0] == true){
                count ++;
                displayTask.setText(count + "");
                setPicture(area4,nameFree);
                setPicture(areaIdle,nameBuffer[4]);
                varBuffer = nameBuffer[4];
                nameBuffer[4] = nameBuffer[0];
                nameBuffer[0] = varBuffer;                
                idle[4] = true;
                idle[0] = false;
            }
            else if(idle[3] == true){
                count ++;
                displayTask.setText(count + "");
                setPicture(area4,nameFree);
                setPicture(area3,nameBuffer[4]);
                varBuffer = nameBuffer[4];
                nameBuffer[4] = nameBuffer[3];
                nameBuffer[3] = varBuffer;
                idle[4] = true;
                idle[3] = false;
            }
            else if(idle[8] == true){
                count ++;
                displayTask.setText(count + "");
                setPicture(area4,nameFree);
                setPicture(area8,nameBuffer[4]);
                varBuffer = nameBuffer[4];
                nameBuffer[4] = nameBuffer[8];
                nameBuffer[8] = varBuffer;
                idle[4] = true;
                idle[8] = false;            
            }
            
        }
        
    }//GEN-LAST:event_area4MouseClicked

    private void areaIdleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaIdleMouseClicked
        // TODO add your handling code here:
        if(idle[0] == false){
            if(idle[4] == true){
                count ++;
                displayTask.setText(count + "");
                setPicture(areaIdle,nameFree);
                setPicture(area4,nameBuffer[0]);
                varBuffer = nameBuffer[0];
                nameBuffer[0] = nameBuffer[4];
                nameBuffer[4] = varBuffer;
                idle[0] = true;
                idle[4] = false;
                checkWin();
            }
        } 
    }//GEN-LAST:event_areaIdleMouseClicked

    private void area3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area3MouseClicked
        // TODO add your handling code here:
        if(idle[3] == false){//thang bam neu ban
            if(idle[4] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area3,nameFree);//xoa anh thang bam
                setPicture(area4,nameBuffer[3]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[3];//thang bam
                nameBuffer[3] = nameBuffer[4];//thang so sanh
                nameBuffer[4] = varBuffer;//thang so sanh
                idle[3] = true;//thang bam chuyen sang ranh
                idle[4] = false;//thang so sanh lai ban
            }
            else if(idle[2] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area3,nameFree);//xoa anh thang bam
                setPicture(area2,nameBuffer[3]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[3];//thang bam
                nameBuffer[3] = nameBuffer[2];//thang so sanh
                nameBuffer[2] = varBuffer;//thang so sanh
                idle[3] = true;//thang bam chuyen sang ranh
                idle[2] = false;//thang so sanh lai ban
            }
            else if(idle[7] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area3,nameFree);//xoa anh thang bam
                setPicture(area7,nameBuffer[3]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[3];//thang bam
                nameBuffer[3] = nameBuffer[7];//thang so sanh
                nameBuffer[7] = varBuffer;//thang so sanh
                idle[3] = true;//thang bam chuyen sang ranh
                idle[7] = false;//thang so sanh lai ban
            }
        }
        
    }//GEN-LAST:event_area3MouseClicked

    private void area2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area2MouseClicked
        // TODO add your handling code here:
        if(idle[2] == false){//thang bam neu ban
            if(idle[3] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area2,nameFree);//xoa anh thang bam
                setPicture(area3,nameBuffer[2]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[2];//thang bam
                nameBuffer[2] = nameBuffer[3];//thang so sanh
                nameBuffer[3] = varBuffer;//thang so sanh
                idle[2] = true;//thang bam chuyen sang ranh
                idle[3] = false;//thang so sanh lai ban
            }
            else if(idle[1] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area2,nameFree);//xoa anh thang bam
                setPicture(area1,nameBuffer[2]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[2];//thang bam
                nameBuffer[2] = nameBuffer[1];//thang so sanh
                nameBuffer[1] = varBuffer;//thang so sanh
                idle[2] = true;//thang bam chuyen sang ranh
                idle[1] = false;//thang so sanh lai ban
            }
            else if(idle[6] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area2,nameFree);//xoa anh thang bam
                setPicture(area6,nameBuffer[2]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[2];//thang bam
                nameBuffer[2] = nameBuffer[6];//thang so sanh
                nameBuffer[6] = varBuffer;//thang so sanh
                idle[2] = true;//thang bam chuyen sang ranh
                idle[6] = false;//thang so sanh lai ban
            }
        }
    }//GEN-LAST:event_area2MouseClicked

    private void area1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area1MouseClicked
        // TODO add your handling code here:
        if(idle[1] == false){//thang bam neu ban
            if(idle[2] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area1,nameFree);//xoa anh thang bam
                setPicture(area2,nameBuffer[1]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[1];//thang bam
                nameBuffer[1] = nameBuffer[2];//thang so sanh
                nameBuffer[2] = varBuffer;//thang so sanh
                idle[1] = true;//thang bam chuyen sang ranh
                idle[2] = false;//thang so sanh lai ban
            }
            else if(idle[5] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area1,nameFree);//xoa anh thang bam
                setPicture(area5,nameBuffer[1]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[1];//thang bam
                nameBuffer[1] = nameBuffer[5];//thang so sanh
                nameBuffer[5] = varBuffer;//thang so sanh
                idle[1] = true;//thang bam chuyen sang ranh
                idle[5] = false;//thang so sanh lai ban
            }
        }
        
    }//GEN-LAST:event_area1MouseClicked

    private void area5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area5MouseClicked
        // TODO add your handling code here:
        if(idle[5] == false){//thang bam neu ban
            if(idle[1] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area5,nameFree);//xoa anh thang bam
                setPicture(area1,nameBuffer[5]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[5];//thang bam
                nameBuffer[5] = nameBuffer[1];//thang so sanh
                nameBuffer[1] = varBuffer;//thang so sanh
                idle[5] = true;//thang bam chuyen sang ranh
                idle[1] = false;//thang so sanh lai ban
            }
            else if(idle[6] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area5,nameFree);//xoa anh thang bam
                setPicture(area6,nameBuffer[5]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[5];//thang bam
                nameBuffer[5] = nameBuffer[6];//thang so sanh
                nameBuffer[6] = varBuffer;//thang so sanh
                idle[5] = true;//thang bam chuyen sang ranh
                idle[6] = false;//thang so sanh lai ban
            }
            else if(idle[9] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area5,nameFree);//xoa anh thang bam
                setPicture(area9,nameBuffer[5]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[5];//thang bam
                nameBuffer[5] = nameBuffer[9];//thang so sanh
                nameBuffer[9] = varBuffer;//thang so sanh
                idle[5] = true;//thang bam chuyen sang ranh
                idle[9] = false;//thang so sanh lai ban
            }
        }
        
    }//GEN-LAST:event_area5MouseClicked

    private void area6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area6MouseClicked
        // TODO add your handling code here:
        if(idle[6] == false){//thang bam neu ban
            if(idle[2] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area6,nameFree);//xoa anh thang bam
                setPicture(area2,nameBuffer[6]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[6];//thang bam
                nameBuffer[6] = nameBuffer[2];//thang so sanh
                nameBuffer[2] = varBuffer;//thang so sanh
                idle[6] = true;//thang bam chuyen sang ranh
                idle[2] = false;//thang so sanh lai ban
            }
            else if(idle[5] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area6,nameFree);//xoa anh thang bam
                setPicture(area5,nameBuffer[6]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[6];//thang bam
                nameBuffer[6] = nameBuffer[5];//thang so sanh
                nameBuffer[5] = varBuffer;//thang so sanh
                idle[6] = true;//thang bam chuyen sang ranh
                idle[5] = false;//thang so sanh lai ban
            }
            else if(idle[10] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area6,nameFree);//xoa anh thang bam
                setPicture(area10,nameBuffer[6]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[6];//thang bam
                nameBuffer[6] = nameBuffer[10];//thang so sanh
                nameBuffer[10] = varBuffer;//thang so sanh
                idle[6] = true;//thang bam chuyen sang ranh
                idle[10] = false;//thang so sanh lai ban
            }
            else if(idle[7] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area6,nameFree);//xoa anh thang bam
                setPicture(area7,nameBuffer[6]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[6];//thang bam
                nameBuffer[6] = nameBuffer[7];//thang so sanh
                nameBuffer[7] = varBuffer;//thang so sanh
                idle[6] = true;//thang bam chuyen sang ranh
                idle[7] = false;//thang so sanh lai ban
            }
        }
    }//GEN-LAST:event_area6MouseClicked

    private void area7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area7MouseClicked
        // TODO add your handling code here:
        if(idle[7] == false){//thang bam neu ban
            if(idle[3] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area7,nameFree);//xoa anh thang bam
                setPicture(area3,nameBuffer[7]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[7];//thang bam
                nameBuffer[7] = nameBuffer[3];//thang so sanh
                nameBuffer[3] = varBuffer;//thang so sanh
                idle[7] = true;//thang bam chuyen sang ranh
                idle[3] = false;//thang so sanh lai ban
            }
            else if(idle[6] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area7,nameFree);//xoa anh thang bam
                setPicture(area6,nameBuffer[7]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[7];//thang bam
                nameBuffer[7] = nameBuffer[6];//thang so sanh
                nameBuffer[6] = varBuffer;//thang so sanh
                idle[7] = true;//thang bam chuyen sang ranh
                idle[6] = false;//thang so sanh lai ban
            }
            else if(idle[11] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area7,nameFree);//xoa anh thang bam
                setPicture(area11,nameBuffer[7]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[7];//thang bam
                nameBuffer[7] = nameBuffer[11];//thang so sanh
                nameBuffer[11] = varBuffer;//thang so sanh
                idle[7] = true;//thang bam chuyen sang ranh
                idle[11] = false;//thang so sanh lai ban
            }
            else if(idle[8] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area7,nameFree);//xoa anh thang bam
                setPicture(area8,nameBuffer[7]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[7];//thang bam
                nameBuffer[7] = nameBuffer[8];//thang so sanh
                nameBuffer[8] = varBuffer;//thang so sanh
                idle[7] = true;//thang bam chuyen sang ranh
                idle[8] = false;//thang so sanh lai ban
            }
        }
    }//GEN-LAST:event_area7MouseClicked

    private void area8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area8MouseClicked
        // TODO add your handling code here:
        if(idle[8] == false){//thang bam neu ban
            if(idle[4] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area8,nameFree);//xoa anh thang bam
                setPicture(area4,nameBuffer[8]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[8];//thang bam
                nameBuffer[8] = nameBuffer[4];//thang so sanh
                nameBuffer[4] = varBuffer;//thang so sanh
                idle[8] = true;//thang bam chuyen sang ranh
                idle[4] = false;//thang so sanh lai ban
            }
            else if(idle[7] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area8,nameFree);//xoa anh thang bam
                setPicture(area7,nameBuffer[8]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[8];//thang bam
                nameBuffer[8] = nameBuffer[7];//thang so sanh
                nameBuffer[7] = varBuffer;//thang so sanh
                idle[8] = true;//thang bam chuyen sang ranh
                idle[7] = false;//thang so sanh lai ban
            }
            else if(idle[12] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area8,nameFree);//xoa anh thang bam
                setPicture(area12,nameBuffer[8]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[8];//thang bam
                nameBuffer[8] = nameBuffer[12];//thang so sanh
                nameBuffer[12] = varBuffer;//thang so sanh
                idle[8] = true;//thang bam chuyen sang ranh
                idle[12] = false;//thang so sanh lai ban
            }
        }
    }//GEN-LAST:event_area8MouseClicked

    private void area9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area9MouseClicked
        // TODO add your handling code here:
        if(idle[9] == false){//thang bam neu ban
            if(idle[5] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area9,nameFree);//xoa anh thang bam
                setPicture(area5,nameBuffer[9]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[9];//thang bam
                nameBuffer[9] = nameBuffer[5];//thang so sanh
                nameBuffer[5] = varBuffer;//thang so sanh
                idle[9] = true;//thang bam chuyen sang ranh
                idle[5] = false;//thang so sanh lai ban
            }
            else if(idle[10] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area9,nameFree);//xoa anh thang bam
                setPicture(area10,nameBuffer[9]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[9];//thang bam
                nameBuffer[9] = nameBuffer[10];//thang so sanh
                nameBuffer[10] = varBuffer;//thang so sanh
                idle[9] = true;//thang bam chuyen sang ranh
                idle[10] = false;//thang so sanh lai ban
            }
        }
    }//GEN-LAST:event_area9MouseClicked

    private void area10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area10MouseClicked
        // TODO add your handling code here:
        if(idle[10] == false){//thang bam neu ban
            if(idle[6] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area10,nameFree);//xoa anh thang bam
                setPicture(area6,nameBuffer[10]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[10];//thang bam
                nameBuffer[10] = nameBuffer[6];//thang so sanh
                nameBuffer[6] = varBuffer;//thang so sanh
                idle[10] = true;//thang bam chuyen sang ranh
                idle[6] = false;//thang so sanh lai ban
            }
            else if(idle[9] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area10,nameFree);//xoa anh thang bam
                setPicture(area9,nameBuffer[10]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[10];//thang bam
                nameBuffer[10] = nameBuffer[9];//thang so sanh
                nameBuffer[9] = varBuffer;//thang so sanh
                idle[10] = true;//thang bam chuyen sang ranh
                idle[9] = false;//thang so sanh lai ban
            }
            else if(idle[11] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area10,nameFree);//xoa anh thang bam
                setPicture(area11,nameBuffer[10]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[10];//thang bam
                nameBuffer[10] = nameBuffer[11];//thang so sanh
                nameBuffer[11] = varBuffer;//thang so sanh
                idle[10] = true;//thang bam chuyen sang ranh
                idle[11] = false;//thang so sanh lai ban
            }
        }
    }//GEN-LAST:event_area10MouseClicked

    private void area11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area11MouseClicked
        // TODO add your handling code here:
        if(idle[11] == false){//thang bam neu ban
            if(idle[7] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area11,nameFree);//xoa anh thang bam
                setPicture(area7,nameBuffer[11]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[11];//thang bam
                nameBuffer[11] = nameBuffer[7];//thang so sanh
                nameBuffer[7] = varBuffer;//thang so sanh
                idle[11] = true;//thang bam chuyen sang ranh
                idle[7] = false;//thang so sanh lai ban
            }
            else if(idle[10] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area11,nameFree);//xoa anh thang bam
                setPicture(area10,nameBuffer[11]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[11];//thang bam
                nameBuffer[11] = nameBuffer[10];//thang so sanh
                nameBuffer[10] = varBuffer;//thang so sanh
                idle[11] = true;//thang bam chuyen sang ranh
                idle[10] = false;//thang so sanh lai ban
            }
            else if(idle[12] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area11,nameFree);//xoa anh thang bam
                setPicture(area12,nameBuffer[11]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[11];//thang bam
                nameBuffer[11] = nameBuffer[12];//thang so sanh
                nameBuffer[12] = varBuffer;//thang so sanh
                idle[11] = true;//thang bam chuyen sang ranh
                idle[12] = false;//thang so sanh lai ban
            }
        }    
    }//GEN-LAST:event_area11MouseClicked

    private void area12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_area12MouseClicked
        // TODO add your handling code here:
        if(idle[12] == false){//thang bam neu ban
            if(idle[8] == true){//thang so sanh neu ranh
                setPicture(area12,nameFree);//xoa anh thang bam
                count ++;
                displayTask.setText(count + "");
                setPicture(area8,nameBuffer[12]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[12];//thang bam
                nameBuffer[12] = nameBuffer[8];//thang so sanh
                nameBuffer[8] = varBuffer;//thang so sanh
                idle[12] = true;//thang bam chuyen sang ranh
                idle[8] = false;//thang so sanh lai ban
            }
            else if(idle[11] == true){//thang so sanh neu ranh
                count ++;
                displayTask.setText(count + "");
                setPicture(area12,nameFree);//xoa anh thang bam
                setPicture(area11,nameBuffer[12]);//thang so sanh hien thi anh thang bam
                varBuffer = nameBuffer[12];//thang bam
                nameBuffer[12] = nameBuffer[11];//thang so sanh
                nameBuffer[11] = varBuffer;//thang so sanh
                idle[12] = true;//thang bam chuyen sang ranh
                idle[11] = false;//thang so sanh lai ban
            }
        }    
    }//GEN-LAST:event_area12MouseClicked
    
    /*
    
    */
    
      public void setPicture(JLabel label,String name){
        try{
           BufferedImage image = ImageIO.read(new File(name));
           int x = label.getSize().width;
           int y = label.getSize().height;
           int ix = image.getWidth();
           int iy = image.getHeight();
           int dx;
           int dy;
           if(x/y > ix/iy){
               dy = y;
               dx = dy*ix/iy;
           } else{
               dx = x;
               dy = dx*iy/ix;
           }
           ImageIcon icon = new ImageIcon(image.getScaledInstance(dx, dy, BufferedImage.SCALE_SMOOTH));
           label.setIcon(icon);
        }catch(IOException ex){
           // Logger.getLogger(ImageDemo.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
  
     public void resetIdle(){
         idle[1] = idle[2] = idle[3] = idle[4] = idle[5] = idle[6]
         = idle[7] = idle[8] = idle[9] = idle[10] = idle[11] = idle[12] = false;
         idle[0] = true;
     } 
    
     public void checkWin(){
         if(    (nameBuffer[0] == nameFree) &&
                (nameBuffer[1] == namePice[1]) &&
                (nameBuffer[2] == namePice[2]) &&
                (nameBuffer[3] == namePice[3]) &&
                (nameBuffer[4] == namePice[4]) &&
                (nameBuffer[5] == namePice[5]) &&
                (nameBuffer[6] == namePice[6]) &&
                (nameBuffer[7] == namePice[7]) &&
                (nameBuffer[8] == namePice[8]) &&
                (nameBuffer[9] == namePice[9]) &&
                (nameBuffer[10] == namePice[10]) &&
                (nameBuffer[11] == namePice[11]) &&
                (nameBuffer[12] == namePice[12])
           ){
             win = true;
             timeWin = countTime;
             taskWin = count;
             testFrame f = new testFrame(timeWin,taskWin);
             f.show();
             f.setSize(650, 550);
             f.setVisible(true);
             f.setResizable(false);
             this.show(false);
             f.setLocation(300, 100);
             
         }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel area1;
    private javax.swing.JLabel area10;
    private javax.swing.JLabel area11;
    private javax.swing.JLabel area12;
    private javax.swing.JLabel area2;
    private javax.swing.JLabel area3;
    private javax.swing.JLabel area4;
    private javax.swing.JLabel area5;
    private javax.swing.JLabel area6;
    private javax.swing.JLabel area7;
    private javax.swing.JLabel area8;
    private javax.swing.JLabel area9;
    private javax.swing.JLabel areaIdle;
    private javax.swing.JButton button;
    private javax.swing.JLabel displayTask;
    private javax.swing.JLabel displayTask1;
    private javax.swing.JLabel displayTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JButton rePlay;
    private javax.swing.JLabel task;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(runtime == true)
            countTime ++;
        displayTime.setText(countTime + "");
    }
}
