/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswing;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author toan
 */
public final class testFrame extends javax.swing.JFrame {
    static int timeWin,taskWin;
    /**
     * Creates new form testFrame
     */
    public testFrame(int x,int y) {
        this.setTitle("");
        
        
        initComponents();
        set();
        this.setSize(550, 430);
        timeWin = x;
        taskWin = y;
        DisplayTimeWin.setText("" + timeWin );
        DisplayTaskWin.setText("" + taskWin );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DisplayTaskWin = new javax.swing.JLabel();
        displayTimeWin = new javax.swing.JLabel();
        DisplayTimeWin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXCELLENT!");
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, -10, 360, 460);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 120, 150, 140);

        jLabel2.setText("TIME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 30, 90, 17);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 57, 0, 20);

        jLabel5.setText("TASK");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 100, 37, 17);
        getContentPane().add(DisplayTaskWin);
        DisplayTaskWin.setBounds(550, 120, 60, 20);
        getContentPane().add(displayTimeWin);
        displayTimeWin.setBounds(550, 50, 0, 20);
        getContentPane().add(DisplayTimeWin);
        DisplayTimeWin.setBounds(550, 50, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new testFrame(timeWin,taskWin).setVisible(true);
        });
        
        //setPicture(jLabel1,"win.jpg");
    }
    public void setPicture(JLabel label,String name){
        try{
           BufferedImage image = ImageIO.read(new File(name));
           int x = label.getSize().width;
           int y = label.getSize().height;
           int ix = image.getWidth();
           int iy = image.getHeight();
           int dx;
           int dy;
           if(x/y > ix/iy){
               dy = y;
               dx = dy*ix/iy;
           } else{
               dx = x;
               dy = dx*iy/ix;
           }
           ImageIcon icon = new ImageIcon(image.getScaledInstance(dx, dy, image.SCALE_SMOOTH));
           label.setIcon(icon);
        }catch(IOException ex){
           // Logger.getLogger(ImageDemo.class.getName()).log(Level.SEVERE,null,ex);
        }
        
    }
    public void set(){
    setPicture(jLabel1,"win.jpg");
    setPicture(jLabel3,"excellent.jpg");
    
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisplayTaskWin;
    private javax.swing.JLabel DisplayTimeWin;
    private javax.swing.JLabel displayTimeWin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
